### ISSUE TITLE
Select a device form factor

### ISSUE THREAD

**Issue by SeanAlling** [SeanAlling/EE-Emerge2021#1]
A major design decision is to decide what form factor the electronic mask needs to take as this will drive the design of all subsystems. There are two form factors that can be selected
1) All in one
1) Mask with attached fan

In the first case, the mask incorporates all components into a single design. Battery, fan, and control are all built into the ask. 

The second case, the mask attaches to an external box that has all the controls, fan, and filters. 

Which form factor should be used for EE-Emerge 2021

**Comment by anelisecho** [comment]
I think the 2nd option would be better for our project.
My reasoning:
1) Having all components attached into one means the _fan will be closer to the customer's ears and the mask as a whole will be heavier_.  Even if we make the fan quiet, the product will still be more unwieldy than a regular mask.  Considering comfort is of large importance when selecting a mask, I believe it would be difficult to create a commercially desirable mask.
2) _Masks and filters need replacement._  If we create the mask all in one, the customer will have to choose to repurchase the entire mask once their filter/mask needs to be changed.  This will be a more intimidating cost than a replacement filter/mask, and drive customers away from our product.  Subscription services have proved to be popular, and we could advertise to our investors that we have repeat customers built into our business model.
3) Having the mask separated into 2 parts will _make it easier to divide work_ for the class.
4) Counterargument: option 1 could be seen as better bc an attached fan is cumbersome.  However, the attached fan unit is not very large and does not appear to be an issue on comments/questions for similarly designed products.  To avoid attachment being an issue, _we could present several options for the fan_ (arm band, lanyard for hanging around the neck, belt clip).  Furthermore, given the trend in consumer products touting customization, this would work in our favor as the customer feels like they get to choose what is most convenient for them.

**Comment by SeanAlling** [comment]
I did a quick internet search and I found the following results. 
**All In One Masks**
1) [02 Flow](https://www.purespadirect.com/O2-Flow-Electronic-Face-Mask-True-HEPA-Carbon-Fi-p/lp-267850.htm)
1) [LG](https://www.reuters.com/article/us-health-coronavirus-southkorea-wearabl/battery-powered-face-mask-seeks-to-fight-covid-and-foggy-glasses-idUSKBN2610GH)
1) [Philips](https://www.philips.com/a-w/about/dutch-design-week-2020/philips-fresh-air-mask.html)

**2 Part Masks**
1) [Broad AirPro](https://www.amazon.com/Broad-AirPro-Powered-Purifying-Respirator/dp/B086Z2B2F8)
1) [Portable Air Purifier](https://www.amazon.com/4WDKING-Rechargeable-Electrical-Purifying-Housework/dp/B0863G5HKX/ref=sr_1_48?dchild=1&keywords=face+mask+respirator&qid=1610434860&sr=8-48)

It seems that compared to when I performed a similar survey last quarter, the all in one masks are more prevalent now. 

One of the benefits of the all in one mask is that they do not have more parts that get in the way (i.e. the tubing). This would make one assume that they are easier to work with. 

I cant find any information on the weight of the masks though. I assume a heaver mask would require better eleatic bands or straps to keep a good fit on ones face.

**Comment by Jan-Tru** [comment]
Personally, I see the all-in-one mask as having more problems for us to deal with. From what I've seen and am assuming, compared to the attached fan form, it is about 50% more expensive, heavier on the face, has a shorter battery life (since the battery would have to be fairly small and lightweight to reduce weight) and it'll be perceived as louder since the fan is essentially right by the ears. However, problems like these are precisely why I think the all-in-one form would be more interesting of a feat and will provide us the most room for noteworthy innovation. Successfully solving at least one or two of these problems will give us an edge on the market. 

Though the attached fan form would be more straightforward in constructing, I can't really come up with significant technical improvements we could make that would differentiate us from the competition, besides having a quieter fan or greatly cutting down the cost. Also, marketing it would be fairly difficult, as I feel that one of the greatest customer deterrents to buying the mask with an attached fan is having a tube stick out of their face, which is implicit to the design. If a focus group, price-blind, was shown pictures of both mask forms and asked to pick one to wear in public, I'm willing to bet that almost everyone will pick the all-in-one. I think that we should go with the option that satisfies the market's needs and wants.

----
Update: Actually, since we have to use the TI MSP430 or MSP432, I think the attached fan with mask form factor would be the most reasonable option for us to go with since holding a microcontroller of that size on your face would be quite cumbersome. 

Update 2: Sean said something below about integrating the launchpads as a custom PCB in a way that will make the all-in-one mask more feasible, so I'm back on that train.

Also, there's a new all-in-one mask from Razor called [Project Hazel](https://www.razer.com/concepts/razer-project-hazel)

**Comment by SeanAlling** [comment]
@Jan-Tru  We can always integrate the MSP430/MSP432 into the mask as a custom PCB is made. This way the TI launchpads wont have to be used.

**Comment by Kevin2k00** [comment]
I have read through both Anelise and Jan's comment, and I would agree with both of them that a design with an attached fan/section is the more plausible route, given the time, money, and expertise needed for an all-in-one design. However, like Jan described, if I am mistaken and we do have enough time, money, and most importantly the expertise (because I personally have little idea on how to actually create all the electronics, let alone in the small enough form factor) then I agree that having an all-in-one mask is the more outstanding option and something we could be proud of as show of feat! The Philips design Sean has linked above, I find is the most pleasing design with a small fan electronics part that I assume can be removed to wash the mask part. 

To end, maybe a compromise we can think of is if it isn't plausible to make an all-in-one design, we could make the latter for now as a say Mark 1, so we have something to show for our efforts and possibly we may learn things to improve on. Then we can come back to the all-in-one design in Mark 2 after, assuming masks are still prevalent then.

**Comment by SeanAlling** [comment]
Initial design mask design shall be umbilical based, mask separate from control box. Decision was made to start with design based upon a class discussion on 15 January 2021.
